"begin_loop:;"
  "lh t0, 0(%[x]);"
  "lh t1, 0(%[h]);"
  "mul t2, t0, t1;"
  "add t2, t2, %[id];"
  "sh t2, 0(%[y]);"
  "addi %[x], %[x], 2;"
  "addi %[h], %[h], 2;"
  "addi %[y], %[y], 2;"
  "addi %[mul_cnt], %[mul_cnt], 1;"
  "addi %[add_cnt], %[add_cnt], 5;"
  "addi %[lw_cnt], %[lw_cnt], 2;"
  "addi %[sw_cnt], %[sw_cnt], 1;"
  "addi %[others_cnt], %[others_cnt], 1;"
  "addi %[arr_size], %[arr_size], -1;"
"bnez %[arr_size], begin_loop;"
